# Generated by Django 3.2.7 on 2021-09-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=30)),
                ('image_alt_description', models.TextField()),
                ('image_url', models.URLField()),
                ('image_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_shop_app.user')),
            ],
        ),
    ]
