# Generated by Django 3.2.6 on 2021-09-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb_url',
            field=models.URLField(default=-2031),
            preserve_default=False,
        ),
    ]
